### ISSUE TITLE
关于中断向量表

### ISSUE THREAD

**Issue by urain39** [95e2/c8vm#1]
c8vm中所有的中断都是软中断

中断具体实现从地址0x2000开始，到0x3FFF结束(8KB)
其中前512个字节为软中断向量表，每个向量占2个字节，指向中断的具体实现

**Comment by 95e2** [comment]
因为8位寄存器的CPU的内存较小的原因，如果使用类似x86的中断方案会造成空间浪费问题
而c8vm中使用的方案是使用512个字节单独指向中断实现，中断完毕以后使用rts命令返回
也就是说c8vm的中断并不对齐，空间使用会有相对的优化

**Comment by uzilla** [comment]
> c8vm中所有的中断都是软中断
> 
> 中断具体实现从地址0x2000开始，到0x3FFF结束(8KB)
> 其中前512个字节为软中断向量表，每个向量占2个字节，指向中断的具体实现

应该是前256个字节。

**Comment by urain39** [comment]
c8vm应该更精简一些，改成16条软中断指令。

**Comment by urain39** [comment]
```asm
ORG #$2020
; SIRQ00(ZP RST)
; for (uint8_t i = 0; i <= 255; i++)
; { *(uint8_t*)i = 0; }
LDA #$00
LDY #$00
SIRQ00_LOOP_00:
    CMP Y, #$FF
    JBT SIRQ00_LOOP_00_END
    INC Y
    JMP SIRQ00_LOOP_00
SIRQ00_LOOP_00_END:
CLC
RTS
```
